spring:
#  数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    userName : root
    password : satomi/317
    url : jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql : true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379

server:
  servlet:
    context-path:
      /sell

wechat:
  mpAppId: wxcbac1a7db0ec3899
  mpAppSecret: b89562aced06608763c09615d0264a8d
  templateId:
    7bxmTXsB7GDksa2yiTQzKY2-zHG6-SYyFYDBkDQT69w

#后台服务内网穿透地址
project-url:
  wechatMpAuthorize: http://yuisamasell.natapp1.cc

